
import numpy as np
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

np.random.seed(7)

n_train = 15 #Here n_train is number of training samples generating the 12 random data points

# Here X_train is generated using uniform distribution between -3 to 3. -3 and
# 3 are the lower and upper limits of the uniform distribution
X_train = np.sort(np.random.uniform(-3,3,size = n_train)).reshape(-1,1) #Here reshape is used to convert 1D array to 2D array 12 x 1

#Here to know the true relationship between X and y without noise
#To get the y values without noise using the cubic function
#y = 0.5 * x^3 - 2x
#Here squeeze is used to convert 2D array to 1D array
y_true_train = 0.5 * X_train.squeeze()**3 - 2 * X_train.squeeze()

#Here to add noise to the true y values to get the observed y values
#Using normal distribution with mean 0 and standard deviation 3.0
y_train = y_true_train + np.random.normal(0,3.0, size=n_train)

#Testing the model 

#Here the linspace is used to generate 100 data points between -3 to 3
X_test = np.linspace(-3,3,200).reshape(-1,1)
y_true_test = 0.5 * X_test.squeeze()**3 - 2 * X_test.squeeze()


#Our goal is to increase the degrees for the Overfitting. Our goal is to encourage overfitting
degree = 15

#Now we will build two models linear regression and ridge regression
#1. Linear Regression Model

linear_model= Pipeline([
    ('poly', PolynomialFeatures(degree=degree, include_bias=False)),
    ('linear', LinearRegression()),
])

ridge_model = Pipeline([
    ('poly', PolynomialFeatures(degree=degree, include_bias=False)),
    ('ridge', Ridge(alpha=10.0)), #Here alpha is the regularization parameter. Which controls the amount of shrinkage and gives a balance between bias and variance
])

#Train both models with the data generated by np 

linear_model.fit(X_train, y_train)
ridge_model.fit(X_train, y_train)

#Predict y values for both models
y_pred_linear = linear_model.predict(X_test)
y_pred_ridge = ridge_model.predict(X_test)

#Calculate Mean Squared Error for both models
mse_linear_train = mean_squared_error(y_train, linear_model.predict(X_train))
mse_ridge_train = mean_squared_error(y_train, ridge_model.predict(X_train))

mse_ridge_test = mean_squared_error(y_true_test, y_pred_ridge)
mse_linear_test = mean_squared_error(y_true_test, y_pred_linear)

#plot the curves for both models
plt.figure(figsize=(12,6))
plt.scatter(X_train, y_train, label='Noisy Training Data')
plt.plot(X_test, y_true_test, label='True Curve (What we wanted) ')
plt.plot(X_test, y_pred_linear, label=f'Linear Regression test (degree={degree})')
plt.plot(X_test, y_pred_ridge, label=f'Ridge Regression test (degree={degree}, alpha=10.0)')

plt.title('Over Fitting Demo ')
plt.xlabel('X')
plt.ylabel('y') 
plt.legend()
plt.grid()
plt.show()

#Print the comparing between linear mse and ridge mse
print('----------------:Mean Squared Error Comparison:----------------')
print(f'Linear Regression Train MSE: {mse_linear_train:.3f}, Test MSE: {mse_linear_test:.3f}')
print('--------------------------------------------------------------')
print(f'Ridge Regression Train MSE: {mse_ridge_train:.3f}, Test MSE: {mse_ridge_test:.3f}')


